config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'dashboards#index'
  resource :dashboards, only: [:index] do
    collection do
      get :about_us
      get :contact_us
      post :submit_contact
    end
  end

  resources :galleries do
    collection do
      post :validate_img_name
      post :import
      get :get_image_count
    end
  end

  namespace :api do
    namespace :v1 do
      post 'users/sign_in_user', to: 'users#sign_in_user'
      post 'users/sign_up_user', to: 'users#sign_up_user'
      delete 'users/destroy', to: 'users#destroy'
      post 'users/forgot_password', to: 'users#forgot_password'
      resource :features, only: [:index] do
        collection do
          post :add_image
          post :contact_us_submit
        end
        member do
          get :get_image
        end
      end
    end
  end

    # having created corresponding controller and action
    #get '*path', to: 'errors#error_404', via: :all
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	before_action :authenticate_user!

  def index
  end

  def contact_us
  	@contact_detail = ContactDetail.new
  end

  def submit_contact
  	@contact_detail = ContactDetail.new(contact_details_params)
  	if @contact_detail.save
      flash[:success] = 'Thank you for letting us know!!!'
      redirect_to root_path
    else
      render :contact_us
    end
  end

  private
  def contact_details_params
  	params.require(:contact_detail).permit(:name, :email, :mobile_number, :description)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboards/about_us.html.haml
.container
  .row
  .col-lg-12
    %h1.page-header
      We Are Maropost
      %small It's Nice to Meet You!
    %p We make the world's best marketing and sales platforms
    Maropost is the leading global provider of on-demand marketing, sales, commerce, and infrastructure solutions. We offer the world’s best marketing and sales cloud platforms combined with industry leading customer support and Cloud’sient success.

    %p
      Maropost was founded in 2011 by CEO and Chairman Ross Andrew Paquette. We are headquartered in Toronto, Canada, with offices in New York, USA, London, U.K., and Chandigarh, India.

    %p
      = succeed "." do
        %strong Maropost is the fastest growing company in Toronto and among the fastest growing companies in North America. In 2016, Maropost was ranked 4th in Deloitte's Canadian Technology Fast 50, 7th in the annual PROFIT 500 of Canada's fastest- growing companies, and 37th in the North America-wide Deloitte Fast 500.
    %p
      = succeed "." do
        Experience the power of Maropost Marketing Cloud’s 1-to-1 digital marketing capabilities firsthand.
  %marquee{:direction => "down"}
    = image_tag "/assets/maropost-img", class: "image_container text-center"
    

app/views/dashboards/contact_us.html.haml
.container
  .row
    .col-md-6
      = form_for(@contact_detail, url: submit_contact_dashboards_path(@contact_detail), class: "form-horizontal") do |f|
        - if @contact_detail.errors.any?
          #error_explanation
            %ul
              - @contact_detail.errors.messages.each do |k,v|
                %li= v[0]

        .form-group
          %label.control-label Name
          = f.text_field :name, placeholder: "enter name", required: :true, class: "form-control"
        .form-group
          = f.label :email, class: "control-label"
          = f.text_field :email, placeholder: "enter email", type: "email", required: :true, class: "form-control"
        .form-group
          = f.label :mobile_number, class: "control-label"
          = f.number_field :mobile_number, placeholder: "enter mobile number", required: true, class: "form-control"
        .form-group
          = f.label :description, class: "control-label"
          = f.text_area :description, placeholder: "enter description", required: true, class: "form-control",style: "resize:none"
          .actions
            = f.submit "Submit", class: "btn btn-primary"
    .col-md-6
      %iframe{:allowfullscreen => "", :frameborder => "0", :height => "450", :src => "https://www.google.com/maps/embed/v1/place?key=AIzaSyD1CbKGlDXYpnHlsB_R0lMspnkMdQCddUI\n    &q=Maropost, University Avenue, Toronto, ON, Canada", :style => "border:0", :width => "600"}

app/views/dashboards/index.html.haml
.container
  %h2 Welcome To Maropost