config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'dashboards#index'
  resource :dashboards, only: [:index] do
    collection do
      get :about_us
      get :contact_us
      post :submit_contact
    end
  end

  resources :galleries do
    collection do
      post :validate_img_name
      post :import
      get :get_image_count
    end
  end

  namespace :api do
    namespace :v1 do
      post 'users/sign_in_user', to: 'users#sign_in_user'
      post 'users/sign_up_user', to: 'users#sign_up_user'
      delete 'users/destroy', to: 'users#destroy'
      post 'users/forgot_password', to: 'users#forgot_password'
      resource :features, only: [:index] do
        collection do
          post :add_image
          post :contact_us_submit
        end
        member do
          get :get_image
        end
      end
    end
  end

    # having created corresponding controller and action
    #get '*path', to: 'errors#error_404', via: :all
end

app/models/gallery.rb
class Gallery < ApplicationRecord
	mount_uploader :attachment, AttachmentUploader
	validates :name, presence: {message: "Please enter name."}
  validates :name, uniqueness: {message: " Name already taken" }
  validates :attachment, presence: {message: "Please attach image."}
  validates :name, :format => { :with => /\A[A-Za-z ][A-Za-z ]*\z/,:message => "Only letters allowed" }

  after_save :clear_cache
  after_destroy :clear_cache

  require 'csv'

  def clear_cache
    $redis.del "galleries"
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
    	gallery = Gallery.new
    	gallery.name = row['name']
    	gallery.remote_attachment_url = row['img_url']
    	if gallery.save
        return "success"
      else
        return invalid.record.errors
      end
    end
  end

  def set_attributes(params)
    self.remote_attachment_url = params[:gallery][:attachment] if params[:gallery] && params[:gallery][:attachment]
    self.name = params[:gallery][:name] if params[:gallery] && params[:gallery][:name]
    self.save
  end

end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :authenticate_user!
  before_action :get_gallery_collection, only: [:index, :destroy]

  def new
  	@gallery = Gallery.new
  end

  def create
  	@gallery = Gallery.new(gallery_params)
  	if @gallery.save
      flash[:success] = 'Picture saved successfully!!!'
      redirect_to galleries_path
    else
      render :new
    end
  end

  def show
    @gallery = Gallery.find_by(id: params[:id])
  end

  def edit
    @gallery = Gallery.find_by(id: params[:id])
  end

  def update
    gallery = Gallery.find_by(id: params[:id])
    if gallery.update(gallery_params)
      flash[:success] = 'Picture Updated Successfully!!!'
      redirect_to galleries_path
    else
      render :edit
    end
  end

  def validate_img_name
    @name = Gallery.where(name: params[:name]).first
  end

  def destroy
    gallery = Gallery.find_by(id: params[:id])
    gallery.destroy if gallery
    galleries =  $redis.get("galleries")
    if galleries.nil?
      galleries = Octopus.using(:shard_one) do
        binding.pry
        Gallery.all.order('created_at DESC').to_json
      end
      # galleries = Gallery.all.order('created_at DESC').to_json
      $redis.set("galleries", galleries)
      $redis.expire("galleries",3.hour.to_i)
    end
    galleries = JSON.load (galleries)
    @galleries = Kaminari.paginate_array(galleries).page(params[:page]).per(6)
  end

  def get_gallery_collection
    #@galleries = Gallery.all.order('created_at DESC').page(params[:page]).per(6)
    galleries =  $redis.get("galleries")
    if galleries.nil?
      galleries = Octopus.using(:shard_one) do
        Gallery.all.order('created_at DESC').to_json
      end
      # galleries = Gallery.all.order('created_at DESC').to_json
      $redis.set("galleries", galleries)
      $redis.expire("galleries",3.hour.to_i)
    end
    galleries = JSON.load (galleries)
    @galleries = Kaminari.paginate_array(galleries).page(params[:page]).per(6)
  end

  def get_image_count
    @count = Gallery.count
    respond_to do |format|
       format.json { render json: @count }
     end
  end

  def import
    begin
      @resp = Gallery.import(params[:file])
      binding.pry
      flash[:success] = 'Gallery imported successfully.!'
      redirect_to galleries_path
    rescue
      binding.pry
      flash[:error] = 'Something wrong with CSV file'
      redirect_to galleries_path
    end
  end

  

  private
  def gallery_params
  	params.require(:gallery).permit(:name, :attachment)
  end


end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_edit_popup.html.haml
#myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1", :style => "display:block;"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title UPDATE GALLERY
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      = form_for(@gallery,method: :patch, remote: true, class: "form-horizontal") do |f|
        .modal-body
          .row
            .col-md-9
              .form-group
                %label.control-label Name
                = f.text_field :name, autocomplete: "off", class: "form-control img-name"
            .col-md-3
              %p.err-text
          .modal-footer
            %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close
            = f.submit "Save changes", class: "btn btn-primary img-name-btn"

app/views/galleries/_image_data.html.haml
//
- galleries.each do |gallery|
  - cache gallery, expires_in: 5.minutes do
    .col-md-3.margin20
      = link_to gallery_path(gallery["id"]) do
        .card{:style => "width: 20rem;"}
          %img.card-img-top{:alt => "Card image cap", :src => "#{gallery["attachment"]["medium"]["url"]}"}/
          .card-block
            %h4.card-title
              = link_to gallery["name"], edit_gallery_path(gallery["id"], :format => :js), remote: true, title: "Click to Edit Name"
            %a.btn.btn-primary.margin10{"data-confirm" => "Are you sure?", "data-method" => "delete", "data-remote" => "true", :href => "#{gallery_path(gallery["id"])}", :rel => "nofollow", title: "Click to Delete"} Delete

app/views/galleries/destroy.js.haml
$('.img_data').html("#{escape_javascript(render 'galleries/image_data', galleries: @galleries)}");

app/views/galleries/edit.js.haml
$('.popup_data').html("#{escape_javascript(render 'galleries/edit_popup')}");
$('#myModal').modal('show');

app/views/galleries/index.html.haml
.container
  .row
    = form_tag import_galleries_path, multipart: true do
      .row
        .col-lg-12
          .col-md-4
            .col-md-2
              = file_field_tag :file, required: :true, class: "import-input"
            .col-md-2
              = submit_tag "Import", class: "btn btn-primary import-submit"
          .col-md-4.text-center.img-count
            .col-md-2.count-text
              ImageCount
            .col-md-2.count-val
          .col-md-4.clearfix.text-center
            = link_to "Add Picture", new_gallery_path, class: "btn btn-primary ad-img"
      .row.text-center
        //- cache 'img_data', expires_in: 5.minutes do
        .img_data
          = render "galleries/image_data", galleries: @galleries
        = paginate @galleries 
  .popup_data

:javascript
  $(document).ready(function(){
    $(".img-count").css("color", "yellow");
    $(".count-val").html('<img src="/assets/AjaxLoader.gif" />');
    if ("#{@galleries.last_page?}" == "true") {
      $(".footer").addClass("navbar-fixed-bottom");
    } else {
      $(".footer").removeClass("navbar-fixed-bottom");
    }
    $.ajax({
      url:'/galleries/get_image_count',
      type:'get',
      success:function(img_count){
        $(".count-val").html(img_count);
        $(".img-count").css("color", "green");
      }
    });
  });

app/views/galleries/new.html.haml
.container
  .row
    .col-md-6
      = form_for(@gallery, class: "form-horizontal") do |f|
        - if @gallery.errors.any?
          #error_explanation
            %ul
              - @gallery.errors.messages.each do |k, v|
                %li= v[0]

        .form-group
          %label.control-label Name
          = f.text_field :name, placeholder: "enter name", autocomplete: "off", class: "form-control"
        .form-group
          = f.label :attachment, class: "control-label"
          = f.file_field :attachment, class: "form-control"
        .actions
          = f.submit "Submit", class: "btn btn-primary"

app/views/galleries/show.html.haml
.container
  .col-md-3.margin20
    .card{:style => "width: 20rem;"}
      %img.card-img-top{:alt => "Card image cap", :src => "#{@gallery.attachment.url(:large)}"}/
      .card-block
        %h4.card-title
          = link_to @gallery.name, edit_gallery_path(@gallery, :format => :js), remote: true, title: "Click to Edit Name"
        = link_to "Back", :back

.popup_data

app/views/galleries/validate_img_name.js.haml
- if params[:name].present?
  - if @name.present?
    $("#gallery_name").css("border-color", "red");
    $(".img-name-btn").attr('disabled','disabled');
    $(".err-text").css("color", "red").html("Already exist"+"&nbsp;"+"<i class='fa fa-times' aria-hidden='true'></i>");
  - else
    $("#gallery_name").css("border-color", "green")
    $(".img-name-btn").removeAttr('disabled');
    $(".err-text").css("color", "green").html("Available"+"&nbsp;"+"<i class='fa fa-check' aria-hidden='true'></i>");
- else
  $("#gallery_name").css("border-color", "");
  $(".err-text").html('');
  $(".img-name-btn").attr('disabled','disabled');