config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'dashboards#index'
  resource :dashboards, only: [:index] do
    collection do
      get :about_us
      get :contact_us
      post :submit_contact
    end
  end

  resources :galleries do
    collection do
      post :validate_img_name
      post :import
      get :get_image_count
    end
  end

  namespace :api do
    namespace :v1 do
      post 'users/sign_in_user', to: 'users#sign_in_user'
      post 'users/sign_up_user', to: 'users#sign_up_user'
      delete 'users/destroy', to: 'users#destroy'
      post 'users/forgot_password', to: 'users#forgot_password'
      resource :features, only: [:index] do
        collection do
          post :add_image
          post :contact_us_submit
        end
        member do
          get :get_image
        end
      end
    end
  end

    # having created corresponding controller and action
    #get '*path', to: 'errors#error_404', via: :all
end

app/views/layouts/_footer.html.haml
%footer.footer
  .text-center
    %hr/
    .row
      .col-lg-12
        .col-md-4
          %p.text-muted
            © 2017 Maropost Inc. All rights reserved. |
            %a{:href => contact_us_dashboards_path} Contact Us
        .col-md-4
          %p.text-muted Terms of Service
        .col-md-4
          %p.text-muted Privacy
/ Fixed navbar

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.active
          %a{:href => "/"} 
            Home
            %span.sr-only (current)
        %li
          = link_to "About Us", about_us_dashboards_path
        %li
          = link_to "Contact Us", contact_us_dashboards_path
        %li
          = link_to "Gallery", galleries_path
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            %a{:href => "javascript:void(0)"}
              = current_user.email
          %li
            = link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'
          %li
            = link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'
        - else
          %li
            = link_to "Sign up", new_user_registration_path, :class => 'navbar-link'
          %li
            = link_to "Login", new_user_session_path, :class => 'navbar-link'

app/views/layouts/_messages.html.haml
- flash.each do |key, value|
  %div{:class => "alert alert-#{key}"}
    %a.close{"data-dismiss" => "alert", :href => "#"} ×
    %ul
      %li
        = value

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Demo
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    = favicon_link_tag 'favicon.ico'
  %body
    = render "layouts/header"
    .container
      .error-flash-msg
        = render 'layouts/messages'
    = yield
    = render "layouts/footer"